### ISSUE TITLE
Login Form UX bad in browser

### ISSUE THREAD

**Issue by xeruf** [invoiceninja/admin-portal#520] opened 2022-12-01 19:35 UTC
I can't autofill the E-Mail, only the password, at least in Firefox.
Using v5.5.42-C100 self-hosted.

**Comment by hillelcoren** [comment] 2022-12-01 19:36
I think this is a duplicate of: https://github.com/invoiceninja/admin-portal/issues/334

Note: the React app shouldn't have this problem, you can try the demo here: https://react.invoicing.co/demo

**Closed by hillelcoren** 2022-12-01 19:36 UTC
