### ISSUE TITLE
Tasks broken: "Invoice Task" button doesn't work. Can't add tasks to invoices. Can't invoice a task.

### ISSUE THREAD

**Issue by mrkylegp** [invoiceninja/admin-portal#404] opened 2022-01-26 03:18 UTC
Confirmed broken also at: https://demo.invoiceninja.com/

Confirmed in Browser, Windows Desktop app and mobile.

The "Invoice Task" button under the task doesn't do anything.

Also can't add the task from the New invoice section. The tick button does nothing, so task's are completely broken for me.

v5.3.49-C73

![Screenshot 2022-01-26 141538](https://user-images.githubusercontent.com/52687659/151098263-74e24f94-28d2-423c-ad5d-80749c63e38d.png)

![Screenshot 2022-01-26 141922](https://user-images.githubusercontent.com/52687659/151099187-837f1711-7a45-4f52-b2e7-7c740f8a319c.png)

The dots menu dropdown under the task and "invoice task" also doesn't work.

![Screenshot 2022-01-26 143513](https://user-images.githubusercontent.com/52687659/151099869-934f618c-136d-4f32-9fab-a4c002ee211a.png)

**Comment by hillelcoren** [comment] 2022-01-26 05:54
Hi,

Thanks for reporting this, the issue is fixed in the next release.

Note: if the task is assigned a project it will work.

**Closed by hillelcoren** 2022-01-26 05:54 UTC
Labels: bug

**Comment by mrkylegp** [comment] 2022-01-26 09:52
> Hi,
> 
> Thanks for reporting this, the issue is fixed in the next release.
> 
> Note: if the task is assigned a project it will work. 

@hillelcoren I don't use projects but will use tasks so it's great to see this will be fixed in the next release.

**Comment by hillelcoren** [comment] 2022-01-26 09:53
New mobile/desktops apps have been released, they should be available in the stores soon...

**Comment by mrkylegp** [comment] 2022-01-26 11:42
> New mobile/desktops apps have been released, they should be available in the stores soon... 

Will the next GitHub release for self hosted be available soon to resolve this issue? Currently still v5.3.49-C73.

**Comment by hillelcoren** [comment] 2022-01-26 11:44
We typically create new GiHub releases every few days

cc @turbo124
