### ISSUE TITLE
Task bug

### ISSUE THREAD

**Issue by sitenzo** [invoiceninja/admin-portal#486] opened 2022-08-21 12:43 UTC
There is a serieus bug in add Task at the moment.
When i set Client and Project and save the taks there is no client at the task anymore.
If i change and set client than there is no project at the task anymore.

![image](https://user-images.githubusercontent.com/52133032/185791315-1c33bbec-6245-48cc-8c8c-47c10b38a798.png)

At this moment it is not possible to set Client and Project for the same task, only one of them

This needs to be fixed on a short term.

Windows App version : v5.5.14-W91
Web App Version : v5.5.14-C91

**Comment by hillelcoren** [comment] 2022-08-21 13:38
Hi,

Is the project assigned to the client? If you change the task client or project the other field is cleared.

**Comment by sitenzo** [comment] 2022-08-21 13:40
> Hi,
> 
> Is the project assigned to the client? If you change the task client or project the other field is cleared.

Yes,
Cant assign Client and Project at the same time, one will be cleared.

**Comment by hillelcoren** [comment] 2022-08-21 13:42
That's by design to ensure the task doesn't belong to a different project than the client. 

If you select a project it will also select the client.

**Comment by sitenzo** [comment] 2022-08-21 13:44
> That's by design to ensure the task doesn't belong to a different project than the client.
> 
> If you select a project it will also select the client.

True, but on save the client will be empty!

**Comment by hillelcoren** [comment] 2022-08-21 13:45
Hmm.. we'll need to look into it

**Comment by hillelcoren** [comment] 2022-08-22 07:41
Thanks for reporting this issue, it should now be corrected.

**Closed by hillelcoren** 2022-08-22 07:41 UTC
Labels: bug

**Comment by sitenzo** [comment] 2022-08-22 10:06
> Thanks for reporting this issue, it should now be corrected.

@hillelcoren It has been fixed, Thanks for the quick response.

**Comment by hillelcoren** [comment] 2022-08-22 10:11
Glad to hear it, thanks for the update!

**Comment by hmnd** [comment] 2022-08-28 08:49
@hillelcoren any idea when the snap for v5.0.92 will go live? Just encountered this bug myself in v5.0.91.

**Comment by hillelcoren** [comment] 2022-08-28 08:50
This is a backend issue, are you using the latest version of the app?

**Comment by hmnd** [comment] 2022-08-28 08:56
Ahh, yup that instantly fixed it. Sorry for the bother!

**Comment by hillelcoren** [comment] 2022-08-28 08:56
No worries, glad to hear it's resolved!
