### ISSUE TITLE
app does not allow for self-signed certs

### ISSUE THREAD

**Issue by mstyp** [invoiceninja/admin-portal#461] opened 2022-07-17 22:25 UTC
My instance runs in a lan, and runs via yunohost on a .local domain. 

It has an https self signed certificate. I can not set it to plain http (yunohost is really anal about https and I dont know how to change it). I can not get a standard lets encrypt cert, since it runs entrily on a lan with no access to broader internet and it does not have a real domain. 

The android app always spits out a "self signed certificate in certificate chain" error. I can log in fine on the browser, but that wont work when I am away from my lan and "offline" (which is a lot of the time). 

I think the standard thing to do here is to ask for a security exception. or least thats what nextcloud does.

**Comment by hillelcoren** [comment] 2022-07-18 03:19
Duplicate of #238

**Closed by hillelcoren** 2022-07-18 03:19 UTC

**Comment by mstyp** [comment] 2022-07-18 12:44
To be unhelpfully appendices, That issue involves insecure http this one involves self signed certs. I cant use insecure http.

**Comment by hillelcoren** [comment] 2022-07-18 21:55
We appreciate pedantic users... I believe it would be the same solution either way.
